# cppcheck
# cpplint
# clang-format
# include-what-you-use
#cmake-lint
# lua-check
# luaformatter

repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cppcheck
      - id: cpplint
      - id: clang-format
      - id: include-what-you-use
  - repo: https://gitlab.com/pablodiehl/pre-commit-lua-formatter
    rev: v1.0.0
    hooks:
      - id: lua-formatter
  - repo: https://github.com/lunarmodules/luacheck
    rev: v1.1.0
    hooks:
      - id: luacheck
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-lint
